### ISSUE TITLE
Urls schema change.

### ISSUE THREAD

**Issue by driv3r** [applift/hasoffersv3#32]
I recently noticed in HO documentation, that they changed the url from

``` curl
https://api.hasoffers.com/v3/Offer.json?Method=methodName
```

to

``` curl
https://api.hasoffers.com/Apiv3/json?Target=TargetName&Method=methodName
```

We should probably update it, WDYS?

**Comment by miry** [comment]
:+1:

**Comment by wowawiwa** [comment]
:+1:   Where did  you see that?

**Comment by hasryan** [comment]
Both URL formats are valid and there are no plans to deprecate either one of them.

**Comment by psychocandy** [comment]
@hasryan how do you know that?

@driv3r I agree. It's not a small change though.

**Comment by hasryan** [comment]
@psychocandy I work on the API and made this change to our documentation.  The alternate `v3/<Target>.json` format was introduced some time ago but did not reach the same level of use as the `Apiv3/json?Target=<Target>` syntax.  I updated our documentation to use the original format that most of our customers were familiar with.  However, since some API clients still use the `v3/<Target>.json` format we will not be removing support for it.  Ideally there would be a single format but it would be rather difficult to consolidate now.
